FROM node:20-alpine

WORKDIR /app

# Copy only package files and install deps
COPY package*.json pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install

# Copy everything (including ts source)
COPY . .

EXPOSE 4000

# Use your existing dev script
CMD ["pnpm", "run", "dev"]
